[package]
name = "jobserver"
version = "0.1.17"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/jobserver-rs"
homepage = "https://github.com/alexcrichton/jobserver-rs"
documentation = "https://docs.rs/jobserver"
description = """
An implementation of the GNU make jobserver for Rust
"""

[target.'cfg(unix)'.dependencies]
libc = "0.2.50"

[target.'cfg(windows)'.dependencies]
getrandom = "0.1.12"

[dev-dependencies]
futures = "0.3"
num_cpus = "1.0"
tempdir = "0.3"
tokio-core = "0.1"
tokio-process = "0.2"

[[test]]
name = "client"
harness = false
path = "tests/client.rs"

[[test]]
name = "server"
path = "tests/server.rs"

[[test]]
name = "client-of-myself"
path = "tests/client-of-myself.rs"
harness = false

[[test]]
name = "make-as-a-client"
path = "tests/make-as-a-client.rs"
harness = false

[[test]]
name = "helper"
path = "tests/helper.rs"
